version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    networks:
      - mynetwork

  assessment:
    image: mrksdh/assessment
    ports:
      - "8081:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
